/*
 * Esta clase selecciona despliega un JFileChooser en el cual puedes selecionar un archivo y enviarlo
 * a una ruta ya especificada.
 */
package soporteMaquinas;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author IlorcitanaRobotica
 */
public class Adjunta_Archivos_M extends javax.swing.JFrame {
    
    File destino;
    String ruta;

    /**
     * Construvtor donde se recoge la ruta donde se van a guardar los archivos Muestra_Archivos 
     * @param ruta
     */
    public Adjunta_Archivos_M(String ruta) {
        initComponents();
        this.setLocationRelativeTo(null);
        destino = new File(ruta);//nuevo destino del fichero
        String m = "";
        this.ruta=ruta;
        KeyboardFocusManager.getCurrentKeyboardFocusManager().
                addKeyEventDispatcher(new KeyEventDispatcher() {
                    @Override
                    public boolean dispatchKeyEvent(KeyEvent e) {
                        if (e.getID() == java.awt.event.KeyEvent.KEY_RELEASED
                                && e.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
                            
                            dispose();
                        }
                        return false;
                    }
                });
    }
   
    /**
     * Constructor del 
     */
    public Adjunta_Archivos_M() {
        initComponents();
        this.setLocationRelativeTo(null);
        KeyboardFocusManager.getCurrentKeyboardFocusManager().
                addKeyEventDispatcher(new KeyEventDispatcher() {
                    @Override
                    public boolean dispatchKeyEvent(KeyEvent e) {
                        if (e.getID() == java.awt.event.KeyEvent.KEY_RELEASED
                                && e.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
                            
                            dispose();
                        }
                        return false;
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooserGuardar = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adjuntar");
        setBackground(new java.awt.Color(102, 255, 102));
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/editor.png")).getImage());

        jFileChooserGuardar.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooserGuardar.setBackground(new java.awt.Color(0, 0, 0));
        jFileChooserGuardar.setCurrentDirectory(new java.io.File("C:\\Users\\jesus portatil\\Desktop"));
        jFileChooserGuardar.setDialogTitle("Abrir ");
        jFileChooserGuardar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jFileChooserGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooserGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooserGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserGuardarActionPerformed
        try {
            File origen = jFileChooserGuardar.getSelectedFile();    //fichero origen.
            String a = jFileChooserGuardar.getName(origen);         //ruta del fichero origen.


            File desdes = new File(ruta + a);
            if (desdes.exists()) {
                int input = JOptionPane.showOptionDialog(null, "El fichero ya existe. ¿Desea reemplazarlo?", a, JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (input == JOptionPane.OK_OPTION) {
                    OutputStream out;
                    try (InputStream in = new FileInputStream(origen)) {
                        out = new FileOutputStream(desdes);
                        byte[] buf = new byte[1024];
                        int len;
                        while ((len = in.read(buf)) > 0) {
                            out.write(buf, 0, len);
                        }
                    }
                    out.close();
                    JOptionPane.showMessageDialog(null, "El archivo se ha reemplazado correctamente.");
                }

            } else {

                OutputStream out;
                try (InputStream in = new FileInputStream(origen)) {
                    out = new FileOutputStream(desdes);
                    byte[] buf = new byte[1024];
                    int len;
                    while ((len = in.read(buf)) > 0) {
                        out.write(buf, 0, len);
                    }
                }
                out.close();
                JOptionPane.showMessageDialog(null, "El archivo se ha guardado correctamente.");
            }
        } catch (IOException ex) {
            Logger.getLogger(Adjunta_Archivos_M.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jFileChooserGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adjunta_Archivos_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Adjunta_Archivos_M().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser jFileChooserGuardar;
    // End of variables declaration//GEN-END:variables
}
