/*
 * Esta clase selecciona despliega un JFileChooser en el cual puedes selecionar un archivo y enviarlo
 * a una ruta ya especificada.
 */
package reparaciones;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author IlorcitanaRobotica
 */
public class Adjunta_ArchivosEnvio extends javax.swing.JFrame {
    
    String ruta;

    /**
     * Construvtor donde se recoge la ruta donde se van a guardar los archivos Muestra_Archivosd_tarea 
     * @param ruta
     */
    public Adjunta_ArchivosEnvio(String ruta) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ruta = ruta;
    }
   
    /**
     * Constructor del 
     */
    public Adjunta_ArchivosEnvio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserGuardar = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adjuntar");
        setBackground(new java.awt.Color(102, 255, 102));
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/satelite_p.png")).getImage());

        jFileChooserGuardar.setAcceptAllFileFilterUsed(false);
        jFileChooserGuardar.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooserGuardar.setApproveButtonToolTipText("");
        jFileChooserGuardar.setBackground(new java.awt.Color(0, 153, 204));
        jFileChooserGuardar.setCurrentDirectory(new java.io.File("C:\\Users\\Diseño\\Desktop"));
        jFileChooserGuardar.setDialogTitle("Abrir ");
        jFileChooserGuardar.setFileHidingEnabled(true);
        jFileChooserGuardar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jFileChooserGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooserGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooserGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserGuardarActionPerformed
        //jFileChooserGuardar.cancelSelection();
        File origen = jFileChooserGuardar.getSelectedFile();    //fichero origen.
        String a = jFileChooserGuardar.getName(origen);         //ruta del fichero origen.
        String b = jFileChooserGuardar.getTypeDescription(origen);
        if (jFileChooserGuardar.accept(origen)){    
            File destino = new File(ruta+"\\"+a);  //nuevo destino del fichero
            //se realiza la copia del fichero origen en destino.
            try {
                InputStream in = new FileInputStream(origen);
                OutputStream out = new FileOutputStream(destino);

                byte[] buf = new byte[1024];
                int len;

                while ((len = in.read(buf)) > 0) {
                    out.write(buf, 0, len);
                }

                in.close();
                out.close();
                JOptionPane.showMessageDialog(null, "El archivo se ha adjuntado correctamente.","Resultado", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }catch (IOException ioe){
                ioe.printStackTrace();
            }
        }
    }//GEN-LAST:event_jFileChooserGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adjunta_ArchivosEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Adjunta_ArchivosEnvio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooserGuardar;
    // End of variables declaration//GEN-END:variables
}
