/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package satation;

import java.io.IOException;
import java.net.ServerSocket;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import reparaciones.Panel_Reparaciones;
import reparaciones.hilosEnvios;
import soporteActas.hilosActas;
import soporteActas.principalActas;
import soporteMaquinas.hilosMaquinas;
import tareasIlorcitana.hilosTareas;

/**
 *
 * @author Diseño
 */
public class PanelStation extends javax.swing.JFrame {
    
    private static ServerSocket SERVER_SOCKET;
    
    /**
     * Creates new form PanelStation.
     */
    public PanelStation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUsuario = new javax.swing.JButton();
        boton_maquinas = new javax.swing.JButton();
        boton_mantenimiento = new javax.swing.JButton();
        boton_tareas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_envio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IlorcitanaStation V1.04.03");
        setBackground(new java.awt.Color(155, 202, 233));
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/satelite_p.png")).getImage());
        setResizable(false);

        botonUsuario.setFont(new java.awt.Font("3ds Light", 1, 18)); // NOI18N
        botonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/z_login.png"))); // NOI18N
        botonUsuario.setToolTipText("Cambiar de usuario");
        botonUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });

        boton_maquinas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        boton_maquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/z_robot_1.png"))); // NOI18N
        boton_maquinas.setText("Máquinas");
        boton_maquinas.setToolTipText("Gestión de máquinas");
        boton_maquinas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton_maquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_maquinasActionPerformed(evt);
            }
        });

        boton_mantenimiento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        boton_mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/z_mantenimiento.png"))); // NOI18N
        boton_mantenimiento.setText("Mantenimiento");
        boton_mantenimiento.setToolTipText("Gestión de mantenimiento");
        boton_mantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mantenimientoActionPerformed(evt);
            }
        });

        boton_tareas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        boton_tareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/z_tarea.png"))); // NOI18N
        boton_tareas.setText("Tareas");
        boton_tareas.setToolTipText("Gestión de tareas");
        boton_tareas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton_tareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tareasActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(205, 216, 223));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/satelite_x.png"))); // NOI18N

        boton_envio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        boton_envio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camion-de-mudanzas.png"))); // NOI18N
        boton_envio.setText("Envio reparar");
        boton_envio.setToolTipText("Gestión de máquinas");
        boton_envio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton_envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envioActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");
        jMenu1.setToolTipText("");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jRadioButtonMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonMenuItem1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Actualizar operarios");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_tareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_maquinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_mantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_envio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_tareas)
                        .addGap(18, 18, 18)
                        .addComponent(boton_mantenimiento)
                        .addGap(18, 18, 18)
                        .addComponent(boton_maquinas)
                        .addGap(18, 18, 18)
                        .addComponent(boton_envio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonUsuario))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_tareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tareasActionPerformed
        hilosTareas mihilo = null;
        try {
            mihilo = new hilosTareas();
            mihilo.start();
        } catch (SQLException ex) {
            Logger.getLogger(hilosTareas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton_tareasActionPerformed

    private void boton_maquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_maquinasActionPerformed
        hilosMaquinas mihilo = null;
        try {
            mihilo = new hilosMaquinas();
            mihilo.start();
            //dispose();
        } catch (SQLException ex) {
            Logger.getLogger(hilosMaquinas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton_maquinasActionPerformed

    private void boton_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mantenimientoActionPerformed
        hilosActas mihilo = null;
        try {
            mihilo = new hilosActas();
            mihilo.start();
        } catch (SQLException ex) {
            Logger.getLogger(principalActas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton_mantenimientoActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        panel_loging p = new panel_loging();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonUsuarioActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        Migración m = new Migración();
        m.main();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void boton_envioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envioActionPerformed
        hilosEnvios mihilo = null;
        try {
            mihilo = new hilosEnvios();
            mihilo.start();
        } catch (SQLException ex) {
            Logger.getLogger(principalActas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton_envioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(PanelStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(PanelStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(PanelStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(PanelStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            SERVER_SOCKET = new ServerSocket(1112);
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
                new PanelStation().setVisible(true);
            });
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "La aplicación ya está abierta.", "IlorcitanaStation", 1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonUsuario;
    private javax.swing.JButton boton_envio;
    private javax.swing.JButton boton_mantenimiento;
    private javax.swing.JButton boton_maquinas;
    private javax.swing.JButton boton_tareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
